{
 "title": "Flux / Cluster Stats",
 "tags": [ "flux" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(gotk_reconcile_condition, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(gotk_reconcile_condition{cluster=\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_reconcile_condition{cluster=\"$cluster\",namespace=~\"$namespace\",type=\"Ready\",status=\"True\",kind=~\"Kustomization|HelmRelease\"})\n-\nsum(gotk_reconcile_condition{cluster=\"$cluster\",namespace=~\"$namespace\",type=\"Ready\",status=\"Deleted\",kind=~\"Kustomization|HelmRelease\"})\n"
    }
   ]
  },
  {
   "title": "Failing Reconcilers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gotk_reconcile_condition{cluster=\"$cluster\",namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"Kustomization|HelmRelease\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Manifests Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(gotk_reconcile_condition{cluster=\"$cluster\",namespace=~\"$namespace\",type=\"Ready\",status=\"True\",kind=~\"GitRepository|HelmRepository|Bucket\"})\n-\nsum(gotk_reconcile_condition{cluster=\"$cluster\",namespace=~\"$namespace\",type=\"Ready\",status=\"Deleted\",kind=~\"GitRepository|HelmRepository|Bucket\"})\n"
    }
   ]
  },
  {
   "title": "Failing Sources",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gotk_reconcile_condition{cluster=\"$cluster\",namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"GitRepository|HelmRepository|Bucket\"})"
    }
   ]
  },
  {
   "title": "Reconciler ops avg. duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{cluster=\"$cluster\",namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind)\n/\nsum(rate(gotk_reconcile_duration_seconds_count{cluster=\"$cluster\",namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind)\n",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Source ops avg. duration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{cluster=\"$cluster\",namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket\"}[5m])) by (kind)\n/\nsum(rate(gotk_reconcile_duration_seconds_count{cluster=\"$cluster\",namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket\"}[5m])) by (kind)\n",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cluster reconciliation readiness",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "gotk_reconcile_condition{cluster=\"$cluster\",namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"Kustomization|HelmRelease\"}"
    }
   ]
  },
  {
   "title": "Source acquisition readiness",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "gotk_reconcile_condition{cluster=\"$cluster\",namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"GitRepository|HelmRepository|Bucket\"}"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Cluster reconciliation duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{cluster=\"$cluster\",namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind, name)\n/\nsum(rate(gotk_reconcile_duration_seconds_count{cluster=\"$cluster\",namespace=~\"$namespace\",kind=~\"Kustomization|HelmRelease\"}[5m])) by (kind, name)\n",
     "legendFormat": "{{kind}}/{{name}}"
    }
   ]
  },
  {
   "title": "Source acquisition duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gotk_reconcile_duration_seconds_sum{cluster=\"$cluster\",namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket\"}[5m])) by (kind, name)\n/\nsum(rate(gotk_reconcile_duration_seconds_count{cluster=\"$cluster\",namespace=~\"$namespace\",kind=~\"GitRepository|HelmRepository|Bucket\"}[5m])) by (kind, name)\n",
     "legendFormat": "{{kind}}/{{name}}"
    }
   ]
  }
 ]
}