{
 "title": "Flux / Control Plane",
 "tags": [ "flux" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(gotk_reconcile_condition, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(gotk_reconcile_condition{cluster=\"$cluster\"}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(go_info{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\".*-controller-.*\"})"
    }
   ]
  },
  {
   "title": "Max Work Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(workqueue_longest_running_processor_seconds{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\".*-controller-.*\"})",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\".*-controller-.*\"})"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\".*-controller-.*\"}[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Kubernetes API Requests Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(rest_client_request_latency_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(rest_client_request_latency_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{cluster=\"$cluster\",namespace=\"$namespace\"}[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Kubernetes API Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{cluster=\"$cluster\",namespace=\"$namespace\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{cluster=\"$cluster\",namespace=\"$namespace\",code!~\"2..\"}[1m]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\".*-controller-.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{cluster=\"$cluster\",namespace=\"$namespace\",pod=~\".*-controller-.*\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Reconciliation Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Cluster Reconciliation Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "workqueue_longest_running_processor_seconds{cluster=\"$cluster\",name=\"kustomization\"}",
     "legendFormat": "kustomization"
    }
   ]
  },
  {
   "title": "Cluster Reconciliations ops/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"$cluster\",controller=\"kustomization\",result!=\"error\"}[1m])) by (controller)",
     "legendFormat": "successful reconciliations"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"$cluster\",controller=\"kustomization\",result=\"error\"}[1m])) by (controller)",
     "legendFormat": "failed reconciliations"
    }
   ]
  },
  {
   "title": "Git Sources ops/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"$cluster\",controller=\"gitrepository\",result!=\"error\"}[1m]))",
     "legendFormat": "successful git pulls"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"$cluster\",controller=\"gitrepository\",result=\"error\"}[1m]))",
     "legendFormat": "failed git pulls"
    }
   ]
  },
  { "title": "Helm Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Helm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(controller_runtime_reconcile_time_seconds_bucket{cluster=\"$cluster\",controller=\"helmrelease\"}[5m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(controller_runtime_reconcile_time_seconds_bucket{cluster=\"$cluster\",controller=\"helmrelease\"}[5m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(controller_runtime_reconcile_time_seconds_bucket{cluster=\"$cluster\",controller=\"helmrelease\"}[5m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Helm Releases ops/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"$cluster\",controller=\"helmrelease\",result!=\"error\"}[1m])) by (controller)",
     "legendFormat": "successful reconciliations"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"$cluster\",controller=\"helmrelease\",result=\"error\"}[1m])) by (controller)",
     "legendFormat": "failed reconciliations "
    }
   ]
  },
  {
   "title": "Helm Charts ops/min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"$cluster\",controller=\"helmchart\",result!=\"error\"}[1m])) by (controller)",
     "legendFormat": "successful chart pulls"
    },
    {
     "expr": "sum(increase(controller_runtime_reconcile_total{cluster=\"$cluster\",controller=\"helmchart\",result=\"error\"}[1m])) by (controller)",
     "legendFormat": "failed chart pulls"
    }
   ]
  }
 ]
}